services:
  postgres:
    image: postgres:16
    container_name: bank_cards_postgres
    environment:
      POSTGRES_DB: bank_cards_db
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - bank_cards_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_user -d bank_cards_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: bank_cards_app
    environment:
      DB_USERNAME: bank_user
      DB_PASSWORD: bank_password
      JWT_SECRET: mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
      ENCRYPTION_KEY: myEncryptionKey123456789012345678901234567890
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bank_cards_network
    volumes:
      - ./logs:/app/logs
    profiles:
      - full

volumes:
  postgres_data:
    driver: local

networks:
  bank_cards_network:
    driver: bridge