server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: bank-cards

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_cards_db
    username: ${DB_USERNAME:bank_user}
    password: ${DB_PASSWORD:bank_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  security:
    user:
      name: admin
      password: admin

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}
  expiration: 86400000 # 24 hours in milliseconds

# Application specific settings
app:
  encryption:
    key: ${ENCRYPTION_KEY:myEncryptionKey123456789012345678901234567890}

# Logging
logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    liquibase: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
