server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

spring:
  application:
    name: bank-cards
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

  liquibase:
    change-log: classpath:db/migration/master.yaml
    enabled: true

  security:
    user:
      name: admin
      password: admin

# JWT Configuration
jwt:
  secret: YbSS/0YQOmauYLHwkyqhQaM0fuGexnIFni3tNG3bpLSSCykNUcART4vHTJWNNdxMTDdOo5R0y+b3gbaxKSlHkQ==

# Application specific settings
app:
  encryption:
    key: ${ENCRYPTION_KEY}
  expiry_date: ${APP_EXPIRY_DATE}

# Logging
logging:
  file:
    name: ${LOG_FILE_PATH}
  logback:
    rolling policy:
      max-history: 5
      max-file-size: 10MB
  level:
    root: ${LOG_LEVEL_ROOT}
    com.example.bankcards: ${LOG_LEVEL_APP}
    org.springframework.security: DEBUG
    org.hibernate.SQL: ERROR
    liquibase: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"