server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: bank-cards
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:postgresql://localhost:6543/bank_rest
    username: root
    password: qwerty
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

  liquibase:
    change-log: classpath:db/migration/master.yaml
    enabled: true

  security:
    user:
      name: admin
      password: admin

# JWT Configuration
jwt:
  secret: YbSS/0YQOmauYLHwkyqhQaM0fuGexnIFni3tNG3bpLSSCykNUcART4vHTJWNNdxMTDdOo5R0y+b3gbaxKSlHkQ==

# Application specific settings
app:
  encryption:
    key: cd0211c7721d48006aff56996fe13e33d2b4924672b3a6aa2d2bf7786bfa0fee
  expiry_date: 3

# Logging
logging:
  file:
    name: logs/app.log
  logback:
    rolling policy:
      max-history: 5
      max-file-size: 10MB
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    liquibase: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
