server:
  port: 9999
  servlet:
    context-path: /api/v1

spring:
  application:
    name: bank-cards
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: public
        jdbc:
          batch_size: 20

  liquibase:
    change-log: classpath:db/migration/master.yaml
    enabled: true

  security:
    user:
      name: admin
      password: admin

jwt:
  secret: ${JWT_SECRET}

app:
  encryption:
    key: ${ENCRYPTION_KEY}
  expiry_date: ${APP_EXPIRY_DATE}


logging:
  file:
    name: ${LOG_FILE_PATH}
  logback:
    rolling policy:
      max-history: 30
      max-file-size: 50MB
      total-size-cap: 1GB
  level:
    root: ${LOG_LEVEL_ROOT}
    com.example.bankcards: ${LOG_LEVEL_APP}
    org.springframework.security: WARN
    org.hibernate.SQL: ERROR
    liquibase: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized